### ISSUE TITLE
Poison Damage also damages armor while "replace_armor" is true

### ISSUE THREAD

**Issue by UndeadZeratul** [FatherToast/NaturalAbsorption#1]
**MC Version**: 1.7.10
**Forge Version**: 10.13.4.1566
**Natural Absorption Version**: 1.2.1

Originally reported in my modpack repo, [here](https://github.com/UndeadZeratul/ThereWillBeBlood/issues/152).

[With Natural Absorption included and config option turned on.](https://cloud.githubusercontent.com/assets/6988914/17122146/9de2d1ca-529e-11e6-8de6-435faf7be01f.png)

[Without Natural Absorption, or with the config turned off.](https://cloud.githubusercontent.com/assets/6988914/17122266/87b930b4-529f-11e6-9f41-f978a9226c0e.png)

As you can see, if I wear any piece of armor while poisoned, and the config to replace armor is turned on, the damage source forces the armor to be damaged as well, even if it doesn't make sense for the original damage source to do so in the first place.

Upon sifting through the mod's source code here, I found [this line](https://github.com/FatherToast/NaturalAbsorption/blob/935417173ba7595dce3a8e3947d10e94bb5124c0/src/main/java/toast/naturalAbsorption/EventHandler.java#L215) that seems to be the cause; it's making an assumption that all damage sources will damage armor.

**Comment by FatherToast** [comment]
This is intended, since damage that would normally ignore armor no longer does when replace_armor is turned on (e.g., poison damage is prevented by absorption).

However, I suppose it would make sense to only base the armor damage on the absorption actually lost, potentially even not count absorption from sources other than armor. Doing this will require a good amount of rewriting on the armor replacement.

I may also add in the option to make normally armor-ignoring damage ignore the absorption added by armor and/or absorption entirely.

**Comment by UndeadZeratul** [comment]
If it can ignore the absorption hearts entirely, I think that would make the most sense in the two mechanics.  If Natural Absorption doesn't override armor, you simply take damage without the reduction.  If it does override armor, you still simply take damage to your actual health rather than the absorption hearts added by your armor.

If no alternative is easily doable or desired, then I can accept it being intentional, as you are right; having your armor completely mitigate the damage done by poison simply because you have a larger health pool to work with defeats the urgency to remove the damage source.

I'm ok with keeping it the way it is for 1.7.10 and having this changed for 1.10 (if your plan is to port your mods, of course), so whatever you feel is right is fine by me.

Thanks for the response!
